spring:
  application:
    name: switchwon-dev-be-homework
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

exchange-rate-api:
  base-url: https://v6.exchangerate-api.com/v6
  api-key: ${EXCHANGE_RATE_API_KEY:1e684ecef600734c8239ff5d}
  request-url: ${exchange-rate-api.base-url}/${exchange-rate-api.api-key}/latest/USD

scheduler:
  exchange-rate:
    fixed-rate: 60000
    initial-delay: 0
